### ISSUE TITLE
How to use with no-NPM project ?

### ISSUE THREAD

**Issue by Elikill58** [talkjs/country-flag-emoji-polyfill#1]
I'm actually on php project that use emote. I don't want to convert my full project for this. I would like to know how I can use your project to fix my issue.

**Comment by eteeselink** [comment]
Good point! Added some docs here: https://github.com/talkjs/country-flag-emoji-polyfill#or-just-with-a-script-tag
And an example here: https://talkjs.github.io/country-flag-emoji-polyfill/examples/no-npm/index.html

skypack <3
