### ISSUE TITLE
0.1.5 breaks Next.js apps - add README note on typeof window check

### ISSUE THREAD

**Issue by rookbreezy** [talkjs/country-flag-emoji-polyfill#11]
0.1.4:

`
polyfillCountryFlagEmojis()
`

0.1.5:

Make sure to check for window if doing server side rendering.
`
if (typeof window !== 'undefined') polyfillCountryFlagEmojis()`

**Comment by rookbreezy** [comment]
Or add window check in the code, just one line needed I think.

**Comment by eteeselink** [comment]
Thanks for your report.

I'm confused that it worked at all in 0.1.4. I think it would've errored out right when you imported the library, no? Reading [this code](https://github.com/koala-interactive/is-emoji-supported/blob/master/src/is-emoji-supported.ts#L47) sure makes it seem so. Can you confirm that this is true?

**Comment by rookbreezy** [comment]
> I think it would've errored out right when you imported the library, no? Reading [this code](https://github.com/koala-interactive/is-emoji-supported/blob/master/src/is-emoji-supported.ts#L47) sure makes it seem so.

I'm guessing it throws inside the try catch, before ctx is set, then returns early.

**Comment by eteeselink** [comment]
ahyes, ofc. thanks. gross, but i guess it works :)

i remember having to do hacks to avoid that in our work setup but maybe our work setup is particularly quirky in this regard :)

anyway! i published a 0.1.6 which should fix this by simply returning false when window is undefined

**Comment by eteeselink** [comment]
can you confirm that it solves matters adequately?

**Comment by rookbreezy** [comment]
Fixed now in my Next.js app
