### ISSUE TITLE
Font file is missing in the latest npm package

### ISSUE THREAD

**Issue by User123698745** [talkjs/country-flag-emoji-polyfill#2]
The current latest npm package 0.1.2 does not include the font file `TwemojiCountryFlags.woff2`. It was included in the previous version 0.1.1.

**Comment by eteeselink** [comment]
Woa, that's not good. I'm otherwise occupied right now, but when I get to it I'll investigate & fix, thanks for the report.

**Comment by eteeselink** [comment]
I just published 0.1.3 which includes the file again, hope this solves it!
