### ISSUE TITLE
Wrong code gets deployed

### ISSUE THREAD

**Issue by User123698745** [talkjs/country-flag-emoji-polyfill#3]
Something in your deployment process is not working. The latest version 0.1.3 no longer contains the change made by commit `e57201f` "Remove flash of invisible text by setting font-display properly" which added `font-display: swap;`. Looks like the npm packages do not get build from the latest master commit like they should.

**Comment by eteeselink** [comment]
Nah, this is just me being an `npm publish` noob. Bumped it once more (cause i can't overwrite an already-published version), can you try 0.1.4 now?

**Comment by User123698745** [comment]
0.1.4 works. `font-display: swap;` and the font file are included. thank you
