### ISSUE TITLE
Need option when you load font even if other emojis don't work.

### ISSUE THREAD

**Issue by Dostoynov** [talkjs/country-flag-emoji-polyfill#6]
If emoji flags is important in project, you need them no matter what. As I do. And I want them to work and draw for every user. Of course don't want to download font, if emojis already works, but I don't want to install [is-emoji-supported](https://github.com/koala-interactive/is-emoji-supported) to make checks by myself as well

So my proposal is that kind of param or prop

**Comment by eteeselink** [comment]
Can you elaborate? Isn’t that exactly what this library does?

**Comment by eteeselink** [comment]
Closing this because of no response. Feel free to reopen if you're able to shed some more light on this.
