### ISSUE TITLE
Issue with Node.js module resolution due to 'exports' field in package.json

### ISSUE THREAD

**Issue by aashishsingla567** [talkjs/country-flag-emoji-polyfill#7]
Hello,

I am encountering an issue when importing your module in my Node.js project (running Node.js v20.4.0).

On attempting import, I receive the error: 
`There are types at '<path>/node_modules/country-flag-emoji-polyfill/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'country-flag-emoji-polyfill' library may need to update its package.json or typings`. 

I believe  this might stem from missing "." path in exports of the package.json

Would you please look into this issue? 

Thanks in advance for your support!

**Comment by eteeselink** [comment]
This is purely a browser package, don't try to run it in Node.js.
