### ISSUE TITLE
State flags not supported

### ISSUE THREAD

**Issue by NightScript370** [talkjs/country-flag-emoji-polyfill#9]
https://emojipedia.org/flag-for-new-york-usny

This should ideally show the state flag, as support was added as early as 2017: https://blog.emojipedia.org/us-state-flag-emojis-now-possible/

Unfortunately, even with this library, I only see a black flag. Is there a way I could fix this?

**Comment by eteeselink** [comment]
I think you misunderstand what this library does. It merely adds support to for country flags on Windows that other platforms already support. I can't find any evidence that the new york state flag is supported on any platform natively, so I think it's well outside the scope of this library.

Also note the word "country" in the name of this library.

**Comment by NightScript370** [comment]
I see. My bad.
